import Link from 'next/link';
import { ArrowDown, ArrowRight, ArrowUpRight, Code2, GraduationCap, Languages, MapPin } from 'lucide-react';
import { copy, courses, experience, localizedPath, profile, techGroups, type Locale } from '@/content/site';
import { featuredProjects } from '@/content/projects';
import { getResumes } from '@/lib/resumes';
import { personSchema } from '@/lib/metadata';
import { Contact, ProjectCard, SectionHeading, SocialLinks } from './shared';
import { ResumeMenu } from './resume-menu';
import { Orbit } from './orbit';

export function Home({ locale }: { locale: Locale }) {
  const es = locale === 'es';
  return <main id="content">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(personSchema()).replace(/</g, '\\u003c') }}/>
    <section className="hero container" aria-labelledby="hero-title">
      <div className="hero-content"><div className="hero-eyebrow mono"><span/>SOFTWARE DEVELOPER</div><h1 id="hero-title">Eduardo<br/><span>Pertuz</span><i>.</i></h1><p className="hero-description">{copy.hero[locale]}</p><p className="hero-stack">Python <span>·</span> Flask <span>·</span> React <span>·</span> Next.js <span>·</span> JavaScript <span>·</span> SQL</p><div className="hero-actions"><Link className="button button-primary" href="#projects">{copy.viewProjects[locale]}<ArrowDown size={17} aria-hidden="true"/></Link><ResumeMenu locale={locale} resumes={getResumes()} hero/></div><SocialLinks locale={locale} icons/></div>
      <Orbit locale={locale}/>
      <div className="hero-bottom"><p className="location"><MapPin size={14} aria-hidden="true"/>{profile.location[locale]}</p><p className="mono hero-focus">FULL STACK <span>/</span> {es ? 'WEB' : 'WEB'} <span>/</span> {es ? 'APIs' : 'APIs'}</p><a href="#about" className="explore-link" aria-label={es ? 'Conocer más sobre Eduardo' : 'Learn more about Eduardo'}><span className="mono">{es ? 'EXPLORAR' : 'EXPLORE'}</span><ArrowDown size={15} aria-hidden="true"/></a></div>
    </section>
    <section className="section container about-section" id="about"><SectionHeading number="01" label={es ? 'SOBRE MÍ' : 'ABOUT'} title={copy.aboutTitle[locale]}/><div className="about-grid"><div className="about-statement"><span className="about-bracket" aria-hidden="true">{'{'}</span><p>{es ? 'Entender el problema.\nDiseñar la lógica.\nConstruir la solución.' : 'Understand the problem.\nDesign the logic.\nBuild the solution.'}</p><span className="about-bracket closing" aria-hidden="true">{'}'}</span><div className="about-caption mono">PYTHON / REACT / NEXT.JS</div></div><div className="about-copy">{copy.about.map((text,i) => <p key={i}>{text[locale]}</p>)}<div className="about-language"><Languages size={19} aria-hidden="true"/><span>{es ? 'Inglés' : 'English'}</span><strong>{profile.english[locale]}</strong></div></div></div></section>
    <section className="section container projects-section" id="projects"><SectionHeading number="02" label={es ? 'PROYECTOS DESTACADOS' : 'SELECTED PROJECTS'} title={copy.projectsTitle[locale]}><p>{copy.projectsLead[locale]}</p></SectionHeading><div className="featured-list">{featuredProjects.map((project,index) => <ProjectCard key={project.slug} project={project} locale={locale} index={index}/>)}</div></section>
    <section className="section experience-section" id="experience"><div className="container"><SectionHeading number="03" label={es ? 'EXPERIENCIA' : 'EXPERIENCE'} title={copy.experienceTitle[locale]}/><div className="timeline">{experience.map((item) => <article className={`experience-row${item.featured ? ' experience-featured' : ''}`} key={item.role.es}><div className="experience-time"><span className="mono">{item.period[locale]}</span><span className="timeline-mark" aria-hidden="true"/></div><div className="experience-content"><p className="experience-type">{item.type[locale]}</p><h3>{item.role[locale]}</h3>{item.organization && <p className="experience-org">{item.organization}</p>}<ul className="experience-points">{item.points.map((point) => <li key={point.es}>{point[locale]}</li>)}</ul><ul className="tag-list">{item.stack.map((tech) => <li key={tech}>{tech}</li>)}</ul></div></article>)}</div></div></section>
    <section className="section container" id="stack"><SectionHeading number="04" label="TECH STACK" title={copy.stackTitle[locale]}/><div className="stack-grid">{techGroups.map((group) => <div key={group.code} className={`stack-group${group.primary ? ' stack-primary' : ''}`}><div><span className="mono">{group.code}</span><h3>{group.title[locale]}</h3>{group.primary && <Code2 size={20} aria-hidden="true"/>}</div><ul>{group.tools.map((tool) => <li key={tool}>{tool}</li>)}</ul></div>)}</div><div className="additional-stack"><span>{es ? 'Experiencia adicional' : 'Additional experience'}</span><p>Jinja <span>·</span> MongoDB <span>·</span> PostgreSQL</p></div></section>
    <section className="section education-section" id="education"><div className="container"><SectionHeading number="05" label={es ? 'EDUCACIÓN & CERTIFICACIONES' : 'EDUCATION & CERTIFICATIONS'} title={copy.educationTitle[locale]}/><div className="education-grid"><div className="degree-card"><GraduationCap size={30} aria-hidden="true"/><div><p className="mono">{es ? 'FORMACIÓN ACADÉMICA' : 'ACADEMIC BACKGROUND'}</p><h3>{es ? 'Desarrollo de Software' : 'Software Development'}</h3></div><span className="mono">2026 — Actualidad</span></div><div className="certifications"><h3 className="certification-label mono">{es ? 'CERTIFICACIONES SELECCIONADAS' : 'SELECTED CERTIFICATIONS'}</h3>{courses.map((course) => <article className="course" key={course.title}><div><span className="course-year mono">{course.year}</span><h4 lang={'es'}>{course.title}</h4><p>{course.author}<span>·</span>{course.hours}</p>{course.credential && <a href={course.credential} target="_blank" rel="noopener noreferrer" aria-label={`${es ? 'Ver credencial' : 'View credential'}: ${course.title}${es ? ' (nueva pestaña)' : ' (new tab)'}`}>{es ? 'Ver credencial' : 'View credential'}<ArrowUpRight size={15} aria-hidden="true"/></a>}</div></article>)}<details className="other-courses"><summary>{es ? 'Más formación' : 'More training'}<span>+</span></summary><p lang="es">SQL: Creación de Bases de Datos</p><small>Formación continua · Desarrollo web</small><a className="text-link" href="https://ude.my/UC-dbf34e12-1135-4c98-b52b-048314abe7d8" target="_blank" rel="noopener noreferrer">{es ? 'Ver credencial' : 'View credential'}<ArrowUpRight size={15} aria-hidden="true"/><span className="sr-only">{es ? ' (nueva pestaña)' : ' (new tab)'}</span></a></details></div></div></div></section>
    <Contact locale={locale}/>
  </main>;
}
