import Image from 'next/image';
import { ArrowDown, Boxes, Braces, CalendarDays, Camera, Check, Database, FileSpreadsheet, Layers3, LockKeyhole, Monitor, PawPrint, Users } from 'lucide-react';
import type { Locale } from '@/content/site';
import type { Project } from '@/content/projects';

export function ProjectVisual({ project, locale, compact = false }: { project: Project; locale: Locale; compact?: boolean }) {
  const es = locale === 'es';
  const kind = project.kind;
  if (kind === 'sifcao' && project.images?.[0]) {
    const screenshot = project.images[0];
    return <div className="project-visual screenshot-visual" aria-hidden="true"><div className="visual-top"><span className="mono">SIFCAO / {es ? 'APLICACIÓN WEB' : 'WEB APPLICATION'}</span><span className="visual-cross">+</span></div><Image src={screenshot.src} alt="" width={screenshot.width} height={screenshot.height} sizes="(max-width: 680px) 90vw, 580px"/><div className="visual-bottom mono"><span>{es ? 'CAPTURA ORIGINAL' : 'ORIGINAL SCREENSHOT'}</span><span>EP.</span></div></div>;
  }
  return <div className={`project-visual visual-${kind}${compact ? ' visual-compact' : ''}`} aria-hidden="true">
    <div className="visual-top"><span className="mono">{kind === 'sifcao' ? (es ? 'SIFCAO / PROCESO' : 'SIFCAO / WORKFLOW') : kind === 'pos' ? (es ? 'POS / ARQUITECTURA' : 'POS / ARCHITECTURE') : kind === 'barberia' ? (es ? 'BARBERÍA / AGENDA' : 'BARBERÍA / SCHEDULING') : kind === 'happypet' ? (es ? 'HAPPYPET / FLUJO' : 'HAPPYPET / APP FLOW') : (es ? 'PROYECTO / RESUMEN' : 'PROJECT / OVERVIEW')}</span><span className="visual-cross">+</span></div>
    {kind === 'sifcao' && <div className="sifcao-diagram"><div className="resource-row">{[es ? 'Materiales' : 'Materials', es ? 'Mano de obra' : 'Labor', es ? 'Maquinaria' : 'Machinery'].map((label) => <span key={label}><Boxes size={16}/>{label}</span>)}</div><div className="connector"/><div className="flow-node emphasis"><Layers3 size={20}/><div><strong>{es ? 'Tarjetas de precio unitario' : 'Unit-price cards'}</strong><small>{es ? 'Recursos + básicos' : 'Resources + basics'}</small></div></div><div className="connector"/><div className="flow-node"><FileSpreadsheet size={20}/><div><strong>{es ? 'Presupuesto de obra' : 'Construction estimate'}</strong><small>{es ? 'Proyectos · Comparación · Reportes' : 'Projects · Comparison · Reports'}</small></div></div><div className="impact-ribbon"><span>{es ? '~15 días' : '~15 days'}</span><span className="impact-line"/><strong>{es ? 'horas' : 'hours'}</strong></div></div>}
    {kind === 'pos' && <div className="pos-diagram"><div className="api-pill mono">HTTP / REST</div><div className="connector"/><div className="layer-stack">{[['01', 'Controllers', es ? 'Peticiones HTTP' : 'HTTP requests'], ['02', 'Services', es ? 'Reglas de negocio' : 'Business rules'], ['03', 'Repositories', es ? 'Acceso a datos' : 'Data access']].map(([n,title,desc]) => <div className="layer" key={n}><span className="mono">{n}</span><strong>{title}</strong><small>{desc}</small></div>)}</div><div className="connector"/><div className="database-node"><Database size={19}/>PostgreSQL</div><div className="diagram-footnote"><LockKeyhole size={13}/>JWT <span>·</span> RBAC <span>·</span> TOTP 2FA</div></div>}
    {kind === 'barberia' && <div className="schedule-diagram"><div className="schedule-request"><CalendarDays size={21}/><div><strong>{es ? 'Solicitud de cita' : 'Appointment request'}</strong><small>{es ? 'Fecha + servicio + duración' : 'Date + service + duration'}</small></div><span className="mono">30 min</span></div><div className="schedule-rules">{[es ? 'Dentro del horario' : 'Within working hours', es ? 'Sin conflictos de agenda' : 'No scheduling conflicts', es ? 'Barbero activo y disponible' : 'Active, available barber'].map((label) => <div key={label}><span><Check size={13}/></span>{label}</div>)}</div><div className="connector"/><div className="flow-node emphasis"><Users size={21}/><div><strong>{es ? 'Asignación automática' : 'Automatic assignment'}</strong><small>{es ? 'Menor carga de citas confirmadas' : 'Fewest confirmed appointments'}</small></div></div><p className="diagram-footnote">{es ? 'Reglas de negocio · C# / .NET' : 'Business rules · C# / .NET'}</p></div>}
    {kind === 'happypet' && <div className="pet-diagram"><div className="pet-flow"><div className="pet-step"><span><Users size={21}/></span><strong>{es ? 'Acceso' : 'Sign in'}</strong></div><div className="pet-flow-line"/><div className="pet-step featured-step"><span><PawPrint size={24}/></span><strong>{es ? 'Pacientes' : 'Patients'}</strong></div><div className="pet-flow-line"/><div className="pet-step"><span><CalendarDays size={21}/></span><strong>{es ? 'Citas' : 'Visits'}</strong></div></div><div className="connector"/><div className="pet-storage"><div><Camera size={21}/><strong>{es ? 'Fotografías' : 'Photos'}</strong><small>PNG / BLOB</small></div><div><Database size={21}/><strong>SQLite</strong><small>{es ? 'Persistencia local' : 'Local persistence'}</small></div></div><p className="diagram-footnote">Kotlin · Java · Android</p></div>}
    {kind === 'residencias' && <div className="generic-diagram"><Users size={33}/><div className="flow-node">{es ? 'Residente · Empresa · Asesores' : 'Resident · Company · Advisors'}</div><ArrowDown size={20}/><div className="flow-node emphasis">{es ? 'Solicitud · Proyecto · Asignación' : 'Application · Project · Assignment'}</div><span className="mono">WINDOWS FORMS / MYSQL</span></div>}
    {kind === 'peliculas' && <div className="generic-diagram"><Monitor size={33}/>{['Windows Forms', 'DTO / DAO', 'MySQL'].map((label, i) => <div className="mini-layer" key={label}><span className="mono">0{i+1}</span>{label}</div>)}<span className="mono">{es ? 'PROYECTO ARCHIVADO' : 'ARCHIVED PROJECT'}</span></div>}
    {kind === 'unity' && <div className="unity-diagram"><Braces size={28}/><div><span>2D</span><span className="unity-divider"/><span>3D</span></div><p>UNITY / C#</p></div>}
    {kind === 'eduardo' && <div className="generic-diagram"><Braces size={33}/><div className="flow-node"><strong>{es ? 'Frontend' : 'Frontend'}</strong><small>React · Next.js · JavaScript</small></div><ArrowDown size={20}/><div className="flow-node emphasis"><strong>{es ? 'Backend & APIs' : 'Backend & APIs'}</strong><small>Python · Flask · REST</small></div><ArrowDown size={20}/><div className="flow-node"><strong>{es ? 'Datos' : 'Data'}</strong><small>MySQL · PostgreSQL · MongoDB</small></div><span className="mono">EDUARDO PERTUZ / SOFTWARE</span></div>}
    <div className="visual-bottom mono"><span>{es ? 'DIAGRAMA CONCEPTUAL' : 'CONCEPTUAL DIAGRAM'}</span><span>EP.</span></div>
  </div>;
}
